module.exports = {
  SESSION_SECRET: process.env.SESSION_SECRET,
  PORT: process.env.PORT,
  AUTH0_DOMAIN: process.env.AUTH0_DOMAIN,
  AUTH0_CLIENT_ID: process.env.AUTH0_CLIENT_ID,
  AUTH0_CLIENT_SECRET: process.env.AUTH0_CLIENT_SECRET,
  AUTH0_CALLBACK_URL: process.env.AUTH0_CALLBACK_URL
};
